<a href="https://colab.research.google.com/github/Group11members/CREDIT-CARD-FRAUD-DETECTION-/blob/main/notebooks/Creditcardfrauddetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2026.7.22)

In [32]:
## 1. Loading the Dataset
#In this section, we download the credit card fraud dataset from Kaggle and load the CSV file into a Pandas DataFrame.

import pandas as pd
import numpy as np
import os
from os import path
import kagglehub

path= kagglehub.dataset_download("nelgiriyewithana/credit-card-fraud-detection-dataset-2023")
print(path)

Using Colab cache for faster access to the 'credit-card-fraud-detection-dataset-2023' dataset.
/kaggle/input/credit-card-fraud-detection-dataset-2023

In [33]:
print("This is the content of the path leading to the dataset:")
print(os.listdir(path))

This is the content of the path leading to the dataset:
['creditcard_2023.csv']

In [34]:
data= pd.read_csv(os.path.join(path, "creditcard_2023.csv"))

In [35]:
df=pd.DataFrame(data)
print(df)

            id        V1        V2        V3        V4        V5        V6  \
0            0 -0.260648 -0.469648  2.496266 -0.083724  0.129681  0.732898
1            1  0.985100 -0.356045  0.558056 -0.429654  0.277140  0.428605
2            2 -0.260272 -0.949385  1.728538 -0.457986  0.074062  1.419481
3            3 -0.152152 -0.508959  1.746840 -1.090178  0.249486  1.143312
4            4 -0.206820 -0.165280  1.527053 -0.448293  0.106125  0.530549
...        ...       ...       ...       ...       ...       ...       ...
568625  568625 -0.833437  0.061886 -0.899794  0.904227 -1.002401  0.481454
568626  568626 -0.670459 -0.202896 -0.068129 -0.267328 -0.133660  0.237148
568627  568627 -0.311997 -0.004095  0.137526 -0.035893 -0.042291  0.121098
568628  568628  0.636871 -0.516970 -0.300889 -0.144480  0.131042 -0.294148
568629  568629 -0.795144  0.433236 -0.649140  0.374732 -0.244976 -0.603493

              V7        V8        V9  ...       V21       V22       V23  \
0       0.519014 -0.130006  0.727159  ... -0.110552  0.217606 -0.134794
1       0.406466 -0.133118  0.347452  ... -0.194936 -0.605761  0.079469
2       0.743511 -0.095576 -0.261297  ... -0.005020  0.702906  0.945045
3       0.518269 -0.065130 -0.205698  ... -0.146927 -0.038212 -0.214048
4       0.658849 -0.212660  1.049921  ... -0.106984  0.729727 -0.161666
...          ...       ...       ...  ...       ...       ...       ...
568625 -0.370393  0.189694 -0.938153  ...  0.167503  0.419731  1.288249
568626 -0.016935 -0.147733  0.483894  ...  0.031874  0.388161 -0.154257
568627 -0.070958 -0.019997 -0.122048  ...  0.140788  0.536523 -0.211100
568628  0.580568 -0.207723  0.893527  ... -0.060381 -0.195609 -0.175488
568629 -0.347613 -0.340814  0.253971  ...  0.534853 -0.291514  0.157303

             V24       V25       V26       V27       V28    Amount  Class
0       0.165959  0.126280 -0.434824 -0.081230 -0.151045  17982.10      0
1      -0.577395  0.190090  0.296503 -0.248052 -0.064512   6531.37      0
2      -1.154666 -0.605564 -0.312895 -0.300258 -0.244718   2513.54      0
3      -1.893131  1.003963 -0.515950 -0.165316  0.048424   5384.44      0
4       0.312561 -0.414116  1.071126  0.023712  0.419117  14278.97      0
...          ...       ...       ...       ...       ...       ...    ...
568625 -0.900861  0.560661 -0.006018  3.308968  0.081564   4394.16      1
568626 -0.846452 -0.153443  1.961398 -1.528642  1.704306   4653.40      1
568627 -0.448909  0.540073 -0.755836 -0.487540 -0.268741  23572.85      1
568628 -0.554643 -0.099669 -1.434931 -0.159269 -0.076251  10160.83      1
568629  0.931030 -0.349423 -1.090974 -1.575113  0.722936  21493.92      1

[568630 rows x 31 columns]

In [36]:
# Inital inspection
# Check the size, columns, data types and general structure of the dataset.

df.head()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-0.260648,-0.469648,2.496266,-0.083724,0.129681,0.732898,0.519014,-0.130006,0.727159,...,-0.110552,0.217606,-0.134794,0.165959,0.126280,-0.434824,-0.081230,-0.151045,17982.10,0
1,1,0.985100,-0.356045,0.558056,-0.429654,0.277140,0.428605,0.406466,-0.133118,0.347452,...,-0.194936,-0.605761,0.079469,-0.577395,0.190090,0.296503,-0.248052,-0.064512,6531.37,0
2,2,-0.260272,-0.949385,1.728538,-0.457986,0.074062,1.419481,0.743511,-0.095576,-0.261297,...,-0.005020,0.702906,0.945045,-1.154666,-0.605564,-0.312895,-0.300258,-0.244718,2513.54,0
3,3,-0.152152,-0.508959,1.746840,-1.090178,0.249486,1.143312,0.518269,-0.065130,-0.205698,...,-0.146927,-0.038212,-0.214048,-1.893131,1.003963,-0.515950,-0.165316,0.048424,5384.44,0
4,4,-0.206820,-0.165280,1.527053,-0.448293,0.106125,0.530549,0.658849,-0.212660,1.049921,...,-0.106984,0.729727,-0.161666,0.312561,-0.414116,1.071126,0.023712,0.419117,14278.97,0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568630 entries, 0 to 568629
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      568630 non-null  int64
 1   V1      568630 non-null  float64
 2   V2      568630 non-null  float64
 3   V3      568630 non-null  float64
 4   V4      568630 non-null  float64
 5   V5      568630 non-null  float64
 6   V6      568630 non-null  float64
 7   V7      568630 non-null  float64
 8   V8      568630 non-null  float64
 9   V9      568630 non-null  float64
 10  V10     568630 non-null  float64
 11  V11     568630 non-null  float64
 12  V12     568630 non-null  float64
 13  V13     568630 non-null  float64
 14  V14     568630 non-null  float64
 15  V15     568630 non-null  float64
 16  V16     568630 non-null  float64
 17  V17     568630 non-null  float64
 18  V18     568630 non-null  float64
 19  V19     568630 non-null  float64
 20  V20     568630 non-null  float64
 21  V21     568630 non-null  float64
 22  V22     568630 non-null  float64
 23  V23     568630 non-null  float64
 24  V24     568630 non-null  float64
 25  V25     568630 non-null  float64
 26  V26     568630 non-null  float64
 27  V27     568630 non-null  float64
 28  V28     568630 non-null  float64
 29  Amount  568630 non-null  float64
 30  Class   568630 non-null  int64
dtypes: float64(29), int64(2)
memory usage: 134.5 MB

In [38]:
df.shape

(568630, 31)

In [39]:
df.describe()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,568630.000000,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,...,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,568630.000000,568630.0
mean,284314.500000,-5.638058e-17,-1.319545e-16,-3.518788e-17,-2.879008e-17,7.997245e-18,-3.958636e-17,-3.198898e-17,2.109273e-17,3.998623e-17,...,4.758361e-17,3.948640e-18,6.194741e-18,-2.799036e-18,-3.178905e-17,-7.497417e-18,-3.598760e-17,2.609101e-17,12041.957635,0.5
std,164149.486121,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,...,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,6919.644449,0.5
min,0.000000,-3.495584e+00,-4.996657e+01,-3.183760e+00,-4.951222e+00,-9.952786e+00,-2.111111e+01,-4.351839e+00,-1.075634e+01,-3.751919e+00,...,-1.938252e+01,-7.734798e+00,-3.029545e+01,-4.067968e+00,-1.361263e+01,-8.226969e+00,-1.049863e+01,-3.903524e+01,50.010000,0.0
25%,142157.250000,-5.652859e-01,-4.866777e-01,-6.492987e-01,-6.560203e-01,-2.934955e-01,-4.458712e-01,-2.835329e-01,-1.922572e-01,-5.687446e-01,...,-1.664408e-01,-4.904892e-01,-2.376289e-01,-6.515801e-01,-5.541485e-01,-6.318948e-01,-3.049607e-01,-2.318783e-01,6054.892500,0.0
50%,284314.500000,-9.363846e-02,-1.358939e-01,3.528579e-04,-7.376152e-02,8.108788e-02,7.871758e-02,2.333659e-01,-1.145242e-01,9.252647e-02,...,-3.743065e-02,-2.732881e-02,-5.968903e-02,1.590123e-02,-8.193162e-03,-1.189208e-02,-1.729111e-01,-1.392973e-02,12030.150000,0.5
75%,426471.750000,8.326582e-01,3.435552e-01,6.285380e-01,7.070047e-01,4.397368e-01,4.977881e-01,5.259548e-01,4.729905e-02,5.592621e-01,...,1.479787e-01,4.638817e-01,1.557153e-01,7.007374e-01,5.500147e-01,6.728879e-01,3.340230e-01,4.095903e-01,18036.330000,1.0
max,568629.000000,2.229046e+00,4.361865e+00,1.412583e+01,3.201536e+00,4.271689e+01,2.616840e+01,2.178730e+02,5.958040e+00,2.027006e+01,...,8.087080e+00,1.263251e+01,3.170763e+01,1.296564e+01,1.462151e+01,5.623285e+00,1.132311e+02,7.725594e+01,24039.930000,1.0

In [40]:
#Checking for missing values
# Check if any column contains empty/missing values.
df.isnull().sum()

id        0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [41]:

#Checking for duplicates
# Check if any transaction appears more than once.
df.duplicated().sum()

np.int64(0)

In [42]:

df.columns

Index(['id', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [43]:
df.dtypes

id          int64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [44]:
# Checking the target column
# Class is what we want the model to predict: legitimate or fraudulent.

df['Class'].value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

In [45]:
df['Class'].value_counts(normalize=True)

Class
0    0.5
1    0.5
Name: proportion, dtype: float64

In [46]:

# Checking transaction amounts
# Check the basic range of transaction amounts for any obvious issues.
df['Amount'].describe()

count    568630.000000
mean      12041.957635
std        6919.644449
min          50.010000
25%        6054.892500
50%       12030.150000
75%       18036.330000
max       24039.930000
Name: Amount, dtype: float64

In [47]:
df['Amount'].min()

50.01

In [48]:
df['Amount'].max()

24039.93

In [49]:
np.isinf(df.select_dtypes(include='number')).sum().sum()

np.int64(0)

In [50]:
(df['Amount'] < 0).sum()

np.int64(0)

In [51]:
#Checking the ID column
# Check if each transaction has a unique ID before deciding whether to drop it.

df['id'].head()

0    0
1    1
2    2
3    3
4    4
Name: id, dtype: int64

In [52]:
print("Number of rows:", len(df))
print("Number of unique IDs:", df['id'].nunique())
print("Are all IDs unique?", df['id'].is_unique)

Number of rows: 568630
Number of unique IDs: 568630
Are all IDs unique? True

In [53]:
# Each transaction has a unique ID, so it is only an identifier and not a useful feature for prediction.
# We will remove it from the data used for modelling.
clean_df = df.drop(columns=['id'])
print(clean_df)

              V1        V2        V3        V4        V5        V6        V7  \
0      -0.260648 -0.469648  2.496266 -0.083724  0.129681  0.732898  0.519014
1       0.985100 -0.356045  0.558056 -0.429654  0.277140  0.428605  0.406466
2      -0.260272 -0.949385  1.728538 -0.457986  0.074062  1.419481  0.743511
3      -0.152152 -0.508959  1.746840 -1.090178  0.249486  1.143312  0.518269
4      -0.206820 -0.165280  1.527053 -0.448293  0.106125  0.530549  0.658849
...          ...       ...       ...       ...       ...       ...       ...
568625 -0.833437  0.061886 -0.899794  0.904227 -1.002401  0.481454 -0.370393
568626 -0.670459 -0.202896 -0.068129 -0.267328 -0.133660  0.237148 -0.016935
568627 -0.311997 -0.004095  0.137526 -0.035893 -0.042291  0.121098 -0.070958
568628  0.636871 -0.516970 -0.300889 -0.144480  0.131042 -0.294148  0.580568
568629 -0.795144  0.433236 -0.649140  0.374732 -0.244976 -0.603493 -0.347613

              V8        V9       V10  ...       V21       V22       V23  \
0      -0.130006  0.727159  0.637735  ... -0.110552  0.217606 -0.134794
1      -0.133118  0.347452  0.529808  ... -0.194936 -0.605761  0.079469
2      -0.095576 -0.261297  0.690708  ... -0.005020  0.702906  0.945045
3      -0.065130 -0.205698  0.575231  ... -0.146927 -0.038212 -0.214048
4      -0.212660  1.049921  0.968046  ... -0.106984  0.729727 -0.161666
...          ...       ...       ...  ...       ...       ...       ...
568625  0.189694 -0.938153 -1.161847  ...  0.167503  0.419731  1.288249
568626 -0.147733  0.483894 -0.210817  ...  0.031874  0.388161 -0.154257
568627 -0.019997 -0.122048 -0.144495  ...  0.140788  0.536523 -0.211100
568628 -0.207723  0.893527 -0.080078  ... -0.060381 -0.195609 -0.175488
568629 -0.340814  0.253971 -0.513556  ...  0.534853 -0.291514  0.157303

             V24       V25       V26       V27       V28    Amount  Class
0       0.165959  0.126280 -0.434824 -0.081230 -0.151045  17982.10      0
1      -0.577395  0.190090  0.296503 -0.248052 -0.064512   6531.37      0
2      -1.154666 -0.605564 -0.312895 -0.300258 -0.244718   2513.54      0
3      -1.893131  1.003963 -0.515950 -0.165316  0.048424   5384.44      0
4       0.312561 -0.414116  1.071126  0.023712  0.419117  14278.97      0
...          ...       ...       ...       ...       ...       ...    ...
568625 -0.900861  0.560661 -0.006018  3.308968  0.081564   4394.16      1
568626 -0.846452 -0.153443  1.961398 -1.528642  1.704306   4653.40      1
568627 -0.448909  0.540073 -0.755836 -0.487540 -0.268741  23572.85      1
568628 -0.554643 -0.099669 -1.434931 -0.159269 -0.076251  10160.83      1
568629  0.931030 -0.349423 -1.090974 -1.575113  0.722936  21493.92      1

[568630 rows x 30 columns]

In [54]:
!git clone https://github.com/Group11members/CREDIT-CARD-FRAUD-DETECTION-.git

Cloning into 'CREDIT-CARD-FRAUD-DETECTION-'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (4/4), done.

In [55]:
%cd /content/CREDIT-CARD-FRAUD-DETECTION-

/content/CREDIT-CARD-FRAUD-DETECTION-

In [63]:
!mkdir notebooks

mkdir: cannot create directory ‘notebooks’: File exists

In [64]:
!ls

notebooks  README.md

In [75]:
!git status

On branch data-cleaning
nothing to commit, working tree clean

In [77]:
## Instructions for the Next Team Member

# I have completed Part 1: Data Loading, Inspection and Initial Cleaning.

# The cleaned dataset is stored in the DataFrame called `clean_df`.

#

# To continue with Part 2, open the latest version of this notebook

# from our GitHub repository:

# Group11members/CREDIT-CARD-FRAUD-DETECTION-

#

# The notebook is inside the `notebooks` folder.

#

# Before editing, make sure you have the latest version from GitHub.

# Continue from this point in the same notebook — do not create a new notebook.

#

# Your section is Part 2: Exploratory Data Analysis (EDA).

# You can use `clean_df` directly because the earlier cells have already

# created it.

#

# When you finish your section, save the notebook and push the updated

# version to GitHub so the next team member can continue from your work.

#

# Important: Only one person should edit and push this notebook at a time.

# Make sure you are working with the latest version before starting.